// Tasks
export const GET_TASKS_START = 'GET_TASKS_START';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAILURE = 'GET_TASKS_START';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';
export const EDIT_TASK_FAILURE = 'EDIT_TASK_FAILURE';
// Url
export const CHANGE_SORT_FIELD_AND_SORT_DIRECTION =
	'CHANGE_SORT_FIELD_AND_SORT_DIRECTION';
export const CHANGE_PAGE_NUMBER = 'CHANGE_PAGE_NUMBER';
// Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// Login
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const CHECK_AUTH_TOKEN = 'CHECK_AUTH_TOKEN';
